spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: first
          predicates:
            - Path=/first/**
          uri: http://localhost:8081
        - id: second
          predicates:
            - Path=/second/**
          uri: http://localhost:8082
        - id: authentication
          predicates:
            - Path=/login/**
          uri: http://localhost:8088
