name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.CONTAINER_DEPLOY }}

    - name: Build and push authentication-service Image
      run: |
        docker build \
          --file authentication/Dockerfile \
          --tag ghcr.io/${{ secrets.GHCR_USERNAME }}/authentication-service:latest \
          authentication
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/authentication-service:latest

    - name: Build and push api-gateway Image
      run: |
        docker build \
          --file gateway/Dockerfile \
          --tag ghcr.io/${{ secrets.GHCR_USERNAME }}/api-gateway:latest \
          gateway
        docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/api-gateway:latest
